name: Broker

concurrency:
  cancel-in-progress: true
  group: "broker-${{github.ref}}"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    secrets: inherit
    uses: ./.github/workflows/tests.yml

  broker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - tests
    steps:
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
