name: Release Trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release_trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Call Test Workflow
      uses: actions/github-script@v3
      with:
        script: |
          const { execSync } = require('child_process');
          execSync('gh workflow run Test');

    - name: Bump version and create tag
      id: tag_version
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git fetch --tags
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        new_tag=$(echo $latest_tag | awk -F. -v OFS=. '{$NF++;print}')
        git tag $new_tag
        git push origin $new_tag

