name: Release
concurrency:
  cancel-in-progress: true
  group: "release-${{github.ref}}"
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        include:
          - platform: ubuntu-latest
            os: [linux, darwin]
            arch: amd64
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4
      - name: Install dependencies
        run: go mod tidy
      - name: Build for ${{ matrix.os }}
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o openapi-31-to-30-converter-${{ matrix.os }}
      - name: Create and Upload Release
        run: |
          id=$(gh release create ${{ github.ref }} ./openapi-31-to-30-converter-${{ matrix.os }} --note 'Release ${{github.ref}}')
          gh release upload $id ./openapi-31-to-30-converter-${{ matrix.os }} --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version and generate changelog
        uses: conventional-changelog/standard-version@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}