name: Release Trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release_trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Call Test Workflow
      uses: ./.github/workflows/test.yml

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
